version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: PEP1
  app1:
    image: ijynx1/pep1_tingeso
    container_name: pep1_tingeso1
    restart: always
    ports:
      - "8091:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PEP1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  app2:
    image: ijynx1/pep1_tingeso
    container_name: pep1_tingeso2
    restart: always
    ports:
      - "8092:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PEP1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  app3:
    image: ijynx1/pep1_tingeso
    container_name: pep1_tingeso3
    restart: always
    ports:
      - "8093:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PEP1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
